version: '3.5'

services:
    webapp:
        build: .
        volumes:
            - ./:/app
        working_dir: /app
        ports:
            - "8000:8000"
        command: python3 main.py --host=0.0.0.0


    webserver:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/

    mongodb:
        image: mongo
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27017"

volumes:
    mongodata: